### ISSUE TITLE
References to PyVBMC need updating

### ISSUE THREAD

**Issue by matt-graham** [acerbilab/vbmc#8]
Now PyVBMC has been publicly released, it would be good to update the text in `README.md` at

https://github.com/acerbilab/vbmc/blob/54ba2cdd6c11d2595b9613557da14573abbb7b92/README.md?plain=1#L33

to point to the PyVBMC repository.

The FAQ in the Wiki also reference porting to other languages and have a dead link to an anchor in the `README.md` file 

https://github.com/acerbilab/vbmc/wiki#are-you-planning-to-port-vbmc-to-other-languages

**Comment by lacerbi** [comment]
Thanks, well-spotted!
FIxed it: https://github.com/acerbilab/vbmc/commit/396d649c3490f1459828ac85f552482869edf41c

and in the Wiki/FAQ as well:
https://github.com/acerbilab/vbmc/wiki#are-you-planning-to-port-vbmc-to-other-languages
